// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4pmdNSIaYxH_8gZL9KX8gx2sIcq-yC_4',
    appId: '1:701972508105:web:a9262d20e6c806092f0c18',
    messagingSenderId: '701972508105',
    projectId: 'bubu-v2',
    authDomain: 'bubu-v2.firebaseapp.com',
    storageBucket: 'bubu-v2.appspot.com',
    measurementId: 'G-TZ5H4JDDT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf1afWbnZpEh9xYOJOxqmlxnoxnD89Z4s',
    appId: '1:701972508105:android:ca910b5e945252c92f0c18',
    messagingSenderId: '701972508105',
    projectId: 'bubu-v2',
    storageBucket: 'bubu-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0FZMYkZDazfodvrfW_gGGp0kWIbib2Y0',
    appId: '1:701972508105:ios:331396a7a01bd5b12f0c18',
    messagingSenderId: '701972508105',
    projectId: 'bubu-v2',
    storageBucket: 'bubu-v2.appspot.com',
    iosBundleId: 'com.example.bubuV2.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0FZMYkZDazfodvrfW_gGGp0kWIbib2Y0',
    appId: '1:701972508105:ios:331396a7a01bd5b12f0c18',
    messagingSenderId: '701972508105',
    projectId: 'bubu-v2',
    storageBucket: 'bubu-v2.appspot.com',
    iosBundleId: 'com.example.bubuV2.RunnerTests',
  );
}
